version: '3.8'

services:
  # Сервис для PostgreSQL
  db:
    image: postgres:16.1 # Образ PostgreSQL
    container_name: filmorate-db # Имя контейнера
    ports:
      - "5432:5432" # Порт базы данных
    volumes:
      - ./postgres-data:/var/lib/postgresql/data # Volume для хранения данных
    environment:
      POSTGRES_DB: filmorate # Имя базы данных
      POSTGRES_USER: dbuser # Имя пользователя
      POSTGRES_PASSWORD: password # Пароль пользователя

  # Сервис для Java-приложения
  app:
    image: openjdk:17-jdk-slim # Образ OpenJDK
    container_name: filmorate-app # Имя контейнера
    build:
      context: . # Контекст сборки (текущая директория)
      dockerfile: Dockerfile # Файл Dockerfile для сборки приложения
    ports:
      - "8080:8080" # Порт для Spring Boot приложения
    depends_on:
      - db # Приложение зависит от базы данных
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/filmorate # URL базы данных
      SPRING_DATASOURCE_USERNAME: dbuser # Имя пользователя
      SPRING_DATASOURCE_PASSWORD: password # Пароль
      SPRING_JPA_HIBERNATE_DDL_AUTO: update # Настройка Hibernate
    volumes:
      - ./target:/app/target # Монтирование папки с JAR-файлом